# Zero-touch (Imager = flash Lite only, NO OS customisation):
#   .\scripts\pi-satellite\prepare-boot.ps1 -Unattended -BootDrive E: `
#     -Hostname netdiag-wired -SshUser netdiag -SshPassword 'your-password' `
#     -EnvSource '.\scripts\pi-satellite\netdiag.env.example' `
#     -GroupsSource '.\scripts\pi-satellite\netdiag.groups.yaml.example'
#
# prepare-boot.ps1 is optional - you can copy bootfs files by hand
# (see scripts/pi-satellite/README.md). Env+groups alone do NOT install Docker.
#
# Token/URL/Mode rewrite netdiag.env only when those params are passed explicitly.
#
# Config + bootstrap on card, install later over SSH:
#   .\scripts\pi-satellite\prepare-boot.ps1 -BootDrive E: -EnvSource '...'
#   .\scripts\pi-satellite\prepare-boot.ps1 -WaitAndBootstrap -SshHost HOST -SshUser USER

param(
    [string] $BootDrive = "",

    [ValidateSet("wired", "wifi")]
    [string] $Mode = "wired",

    [string] $CoordinatorUrl = "http://192.168.1.10:8787/ingest",
    [string] $Token = "change-me",

    [string] $EnvSource = "",
    [string] $GroupsSource = "",

    # Zero-touch: generate user-data + network-config + ship bootstrap.sh
    [switch] $Unattended,

    [string] $Hostname = "",
    [string] $SshUser = "netdiag",
    [string] $SshPassword = "",
    [string] $SshPubkey = "",
    [string] $WifiSsid = "",
    [string] $WifiPassword = "",
    [string] $Timezone = "Europe/Berlin",

    # Legacy: copy static stub (prefer -Unattended). Overwrites Imager user-data.
    [switch] $IncludeCloudInitUserData,
    [string] $UserDataSource = "",

    [switch] $WaitAndBootstrap,
    [string] $SshHost = "",
    [int] $WaitTimeoutSec = 300
)

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path

if ($Unattended -and -not $BootDrive) {
    throw "-Unattended requires -BootDrive (path to the SD bootfs volume, e.g. E:)"
}

function Write-Utf8Lf([string] $Path, [string] $Text) {
    $normalized = $Text -replace "`r`n", "`n" -replace "`r", "`n"
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $normalized, $utf8NoBom)
}

function Escape-YamlDoubleQuoted([string] $Value) {
    return ($Value -replace '\\', '\\' -replace '"', '\"')
}

function New-CloudInitUserData {
    param(
        [string] $HostName,
        [string] $User,
        [string] $Password,
        [string] $Pubkey,
        [string] $Tz
    )

    $sshAuth = @()
    if ($Pubkey) {
        $keyLine = ($Pubkey.Trim() -replace "`r", "").Trim()
        $sshAuth += "    ssh_authorized_keys:"
        $sshAuth += "      - $keyLine"
    }

    $passwdBlock = ""
    $sshPwauth = "false"
    if ($Password) {
        $pw = Escape-YamlDoubleQuoted $Password
        $passwdBlock = @"
    lock_passwd: false
    plain_text_passwd: "$pw"
"@
        $sshPwauth = "true"
    } else {
        $passwdBlock = "    lock_passwd: true"
    }

    $sshAuthText = if ($sshAuth.Count) { ($sshAuth -join "`n") + "`n" } else { "" }

    return @"
#cloud-config
# Generated by prepare-boot.ps1 -Unattended - do not use Imager OS customisation
# with this card (Imager would overwrite user-data).
hostname: $HostName
manage_etc_hosts: true
timezone: $Tz
package_update: true
packages:
  - curl
  - ca-certificates

users:
  - name: $User
    groups: [sudo, adm]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
$passwdBlock
$sshAuthText
ssh_pwauth: $sshPwauth
enable_ssh: true

write_files:
  - path: /usr/local/sbin/netdiag-firstboot.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -euo pipefail
      FLAG=/var/lib/netdiag-firstboot.done
      LOG=/var/log/netdiag-firstboot.log
      exec >>"\$LOG" 2>&1
      [[ -f "\$FLAG" ]] && exit 0
      mkdir -p /var/lib
      echo "netdiag-firstboot: waiting for network..."
      for i in \$(seq 1 60); do
        if ping -c1 -W2 1.1.1.1 >/dev/null 2>&1 || ping -c1 -W2 8.8.8.8 >/dev/null 2>&1; then
          break
        fi
        sleep 5
      done
      SCRIPT=""
      for p in /boot/firmware/netdiag-bootstrap.sh /boot/netdiag-bootstrap.sh; do
        if [[ -f "\$p" ]]; then SCRIPT="\$p"; break; fi
      done
      mkdir -p /tmp
      if [[ -n "\$SCRIPT" ]]; then
        echo "netdiag-firstboot: using \$SCRIPT"
        sed 's/\r\$//' "\$SCRIPT" > /tmp/netdiag-bootstrap.sh
      else
        echo "netdiag-firstboot: bootfs bootstrap missing - curl fallback"
        ok=0
        for i in \$(seq 1 20); do
          if curl -fsSL --connect-timeout 10 https://raw.githubusercontent.com/Emil007/netdiag/main/scripts/pi-satellite/bootstrap.sh -o /tmp/netdiag-bootstrap.sh; then
            ok=1
            break
          fi
          sleep 15
        done
        [[ "\$ok" -eq 1 ]] || { echo "netdiag-firstboot: failed to fetch bootstrap"; exit 1; }
      fi
      chmod +x /tmp/netdiag-bootstrap.sh
      bash /tmp/netdiag-bootstrap.sh
      touch "\$FLAG"
      echo "netdiag-firstboot: done"

runcmd:
  - [ bash, /usr/local/sbin/netdiag-firstboot.sh ]
"@
}

function New-NetworkConfig {
    param(
        [string] $Ssid,
        [string] $Password
    )
    $ssidEsc = Escape-YamlDoubleQuoted $Ssid
    $passEsc = Escape-YamlDoubleQuoted $Password
    return @"
version: 2
ethernets:
  eth0:
    dhcp4: true
    optional: true
wifis:
  wlan0:
    dhcp4: true
    optional: true
    access-points:
      "$ssidEsc":
        password: "$passEsc"
"@
}

if ($BootDrive) {
    $boot = $BootDrive.TrimEnd("\")
    if (-not (Test-Path $boot)) { throw "Boot drive not found: $boot" }

    if ($Unattended) {
        if (-not $SshPassword -and -not $SshPubkey) {
            throw "-Unattended requires -SshPassword and/or -SshPubkey (no default password is written)"
        }
        $effectiveMode = $Mode
        if (-not $PSBoundParameters.ContainsKey('Mode') -and $EnvSource -and (Test-Path $EnvSource)) {
            $m = Select-String -Path $EnvSource -Pattern '^\s*NETDIAG_MODE=(.+)$' | Select-Object -First 1
            if ($m) { $effectiveMode = $m.Matches.Groups[1].Value.Trim().Trim('"') }
        }
        if ($effectiveMode -eq "wifi") {
            if (-not $WifiSsid -or -not $WifiPassword) {
                throw "-Mode wifi with -Unattended requires -WifiSsid and -WifiPassword"
            }
        }
        if (-not $Hostname) {
            $Hostname = if ($effectiveMode -eq "wifi") { "netdiag-wifi" } else { "netdiag-wired" }
        }
    }

    if (-not $EnvSource) { $EnvSource = Join-Path $here "netdiag.env.example" }
    if (-not $GroupsSource) { $GroupsSource = Join-Path $here "netdiag.groups.yaml.example" }

    $envText = Get-Content -Raw $EnvSource
    if ($PSBoundParameters.ContainsKey('Mode')) {
        $envText = $envText -replace "(?m)^NETDIAG_MODE=.*$", "NETDIAG_MODE=$Mode"
    }
    if ($PSBoundParameters.ContainsKey('CoordinatorUrl')) {
        $envText = $envText -replace "(?m)^NETDIAG_COORDINATOR_URL=.*$", "NETDIAG_COORDINATOR_URL=$CoordinatorUrl"
    }
    if ($PSBoundParameters.ContainsKey('Token')) {
        $envText = $envText -replace "(?m)^NETDIAG_TOKEN=.*$", "NETDIAG_TOKEN=$Token"
    }
    Write-Utf8Lf "$boot\netdiag.env" $envText

    Copy-Item -Force $GroupsSource "$boot\netdiag.groups.yaml"

    $bootstrapSrc = Join-Path $here "bootstrap.sh"
    if (-not (Test-Path $bootstrapSrc)) { throw "bootstrap.sh missing at $bootstrapSrc" }
    $bootstrapText = Get-Content -Raw $bootstrapSrc
    Write-Utf8Lf "$boot\netdiag-bootstrap.sh" $bootstrapText

    if ($Unattended) {
        $userData = New-CloudInitUserData -HostName $Hostname -User $SshUser -Password $SshPassword -Pubkey $SshPubkey -Tz $Timezone
        Write-Utf8Lf "$boot\user-data" $userData

        $meta = @"
instance-id: netdiag-$Hostname
local-hostname: $Hostname
"@
        Write-Utf8Lf "$boot\meta-data" $meta

        $effMode = $Mode
        if (-not $PSBoundParameters.ContainsKey('Mode')) {
            $m = Select-String -Path "$boot\netdiag.env" -Pattern '^\s*NETDIAG_MODE=(.+)$' | Select-Object -First 1
            if ($m) { $effMode = $m.Matches.Groups[1].Value.Trim().Trim('"') }
        }
        if ($effMode -eq "wifi") {
            Write-Utf8Lf "$boot\network-config" (New-NetworkConfig -Ssid $WifiSsid -Password $WifiPassword)
        } elseif (Test-Path "$boot\network-config") {
            Remove-Item -Force "$boot\network-config" -ErrorAction SilentlyContinue
        }

        Write-Host "Zero-touch bootfs ready -> $boot"
        Write-Host "  user-data, meta-data, netdiag.env, netdiag.groups.yaml, netdiag-bootstrap.sh"
        if ($effMode -eq "wifi") { Write-Host "  network-config (Wi-Fi)" }
        Write-Host "Imager: flash Lite only - skip OS customisation (this script owns user-data)."
        Write-Host "Eject, insert Pi, power on. Satellite starts on first boot (no SSH required)."
        Write-Host ("Optional later login: {0}@{1} (or .local) - password/key as you set." -f $SshUser, $Hostname)
    }
    elseif ($IncludeCloudInitUserData) {
        if (-not $UserDataSource) { $UserDataSource = Join-Path $here "cloud-init.user-data" }
        Copy-Item -Force $UserDataSource "$boot\user-data"
        Write-Host "WARNING: copied static user-data (prefer -Unattended). May replace Imager settings."
        Write-Host "Wrote netdiag.env + groups + netdiag-bootstrap.sh -> $boot"
    }
    else {
        Write-Host "Wrote netdiag.env + netdiag.groups.yaml + netdiag-bootstrap.sh -> $boot"
        Write-Host "NOTE: no user-data - Docker/satellite are NOT installed until bootstrap runs."
        Write-Host "  Next: SSH and run sudo bash /boot/firmware/netdiag-bootstrap.sh"
        Write-Host "  Or use -WaitAndBootstrap / -Unattended."
    }
}

if ($WaitAndBootstrap) {
    if (-not $SshHost) { throw "-SshHost required with -WaitAndBootstrap (hostname or IP)" }
    $user = $SshUser
    $deadline = (Get-Date).AddSeconds($WaitTimeoutSec)
    Write-Host "Waiting for $SshHost ..."
    do {
        try {
            if (Test-Connection -ComputerName $SshHost -Count 1 -Quiet -ErrorAction SilentlyContinue) { break }
        } catch {}
        Start-Sleep -Seconds 3
        if ((Get-Date) -gt $deadline) { throw "Timed out waiting for $SshHost" }
    } while ($true)

    Write-Host "Running bootstrap over SSH (password prompt possible)..."
    $cmd = @'
set -e
SCRIPT=""
for p in /boot/firmware/netdiag-bootstrap.sh /boot/netdiag-bootstrap.sh; do
  [ -f "$p" ] && SCRIPT=$p && break
done
if [ -n "$SCRIPT" ]; then
  sed 's/\r$//' "$SCRIPT" > /tmp/netdiag-bootstrap.sh
  sudo bash /tmp/netdiag-bootstrap.sh
else
  curl -fsSL https://raw.githubusercontent.com/Emil007/netdiag/main/scripts/pi-satellite/bootstrap.sh | sudo bash
fi
'@
    ssh -o StrictHostKeyChecking=accept-new "${user}@${SshHost}" $cmd
}
